update deploy script

diff --git a/.github/workflows/deploy_blog.yml b/.github/workflows/deploy_blog.yml
--- a/.github/workflows/deploy_blog.yml
+++ b/.github/workflows/deploy_blog.yml
@@ -23,4 +23,4 @@ jobs:
         key: ${{ secrets.KEY }}
         port: ${{ secrets.PORT }}
         script: |
-          export PATH=$PATH:/usr/local/bin && cd ${{ secrets.DEPLOY_PATH }} && hugo > /dev/null 2>&1 && cd public && jq -c '.[]' index.json| algolia -p blog.catbaron.com objects import blog.catbaron.com -F -
+          export PATH=$PATH:/usr/local/bin && cd ${{ secrets.DEPLOY_PATH }} && (hugo || echo "hugo failed")  && cd public && jq -c '.[]' index.json| algolia -p blog.catbaron.com objects import blog.catbaron.com -F -
